### ISSUE TITLE
Cannot git clone and build longTR

### ISSUE THREAD

**Issue by Owuorgpo** [gymrek-lab/LongTR#18]
Cloning into 'spoa'...
Warning: Permanently added the ECDSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
make: *** [Makefile:95: SPOA] Error 128

**Comment by heliziii** [comment]
Hi,

You probably haven't set up your machine on GitHub. Please follow the instructions here:

https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey

Best,
Helia

**Comment by fanavarro** [comment]
I faced this problem yesterday, I'll post my solution although this issue is already closed. The makefile tries to download a GIT repository by using the SSH protocol, which requires an SSH key to be used. The line is the following one:

```
cd lib && git clone git@github.com:rvaser/spoa.git && cd ..;\
```

However, if we use the https protocol, the repository can be downloaded without any extra configuration. I changed the previous line by the following one to make it work:

```
cd lib && git clone https://github.com/rvaser/spoa.git && cd ..;\
```

This change only implies downloading the spoa git repository by using HTTPS instead of SSH protocol.

Actually, I've just checked that the [pull request 26](https://github.com/gymrek-lab/LongTR/pull/26/) fix this.
