### ISSUE TITLE
"Aborting genotyping of the locus as the sequence upstream/downstream of the repeat is too repetitive for accurate genotyping"

### ISSUE THREAD

**Issue by bw2** [gymrek-lab/LongTR#6]
I'm testing LongTR and finding it to be very accurate on the loci it genotypes. 

<img width="1558" alt="image" src="https://github.com/gymrek-lab/LongTR/assets/6240170/ba7c5492-4c2c-43f3-aec5-22c825763f1f">

However, it only genotypes ~83% of the loci in my input repeats bed file (which I generated by identifying all polymorphic TR loci in my sample within well-behaved regions of the genome). The other 17% are left as no-call due to this error:  "Aborting genotyping of the locus as the sequence upstream/downstream of the repeat is too repetitive for accurate genotyping". 
I understand this is carried over from HipSTR, but given the much longer reads now, would it be possible to convert this to a warning or flag and genotype all loci that have sufficient coverage?

**Comment by heliziii** [comment]
Hi Ben,

Thank you very much for using LongTR. Did you add --skip-assembly parameter when running LongTR? Adding this should skip the step where LongTR tries to assemble the flanking sequence, which as you mentioned is not necessary in most cases with long reads. Please let me know if the issue is not fixed after this change.

**Comment by bw2** [comment]
Thanks @heliziii that fixed it!  
Great accuracy even with `--skip-assembly`:
<img width="1635" alt="image" src="https://github.com/gymrek-lab/LongTR/assets/6240170/448a4cdc-d1fd-4bd8-bbd3-88341d0396b5">
